<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Neo Script</string>
	<key>scopeName</key>
	<string>source.neoscript</string>
	<key>fileTypes</key>
	<array>
		<string>ns</string>
	</array>
	<key>patterns</key>
	<array>
		<dict><key>include</key><string>#comments</string></dict>
		<dict><key>include</key><string>#strings</string></dict>
		<dict><key>include</key><string>#function-declarations</string></dict>
		<dict><key>include</key><string>#class-declarations</string></dict>
		<dict><key>include</key><string>#variable-declarations</string></dict>
		<dict><key>include</key><string>#keywords</string></dict>
		<dict><key>include</key><string>#constants</string></dict>
		<dict><key>include</key><string>#numbers</string></dict>
		<dict><key>include</key><string>#function-calls</string></dict>
		<dict><key>include</key><string>#operators</string></dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.neoscript</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.neoscript</string>
					<key>match</key>
					<string>//.*$</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.neoscript</string>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict><key>name</key><string>punctuation.definition.string.begin.neoscript</string></dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict><key>name</key><string>punctuation.definition.string.end.neoscript</string></dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.neoscript</string>
							<key>match</key>
							<string>\\(?:[\\'"abfnrtv0]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4})</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.neoscript</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
				</dict>
			</array>
		</dict>
		<key>function-declarations</key>
		<dict>
			<key>name</key>
			<string>meta.function.neoscript</string>
			<key>match</key>
			<string>\b(export\s+)?(fun)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.modifier.export.neoscript</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.type.function.neoscript</string></dict>
				<key>3</key>
				<dict><key>name</key><string>entity.name.function.neoscript</string></dict>
			</dict>
		</dict>
		<key>class-declarations</key>
		<dict>
			<key>name</key>
			<string>meta.class.neoscript</string>
			<key>match</key>
			<string>\b(class)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.class.neoscript</string></dict>
				<key>2</key>
				<dict><key>name</key><string>entity.name.type.class.neoscript</string></dict>
			</dict>
		</dict>
		<key>variable-declarations</key>
		<dict>
			<key>name</key>
			<string>meta.variable.neoscript</string>
			<key>match</key>
			<string>\b(var)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.variable.neoscript</string></dict>
				<key>2</key>
				<dict><key>name</key><string>variable.other.neoscript</string></dict>
			</dict>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.neoscript</string>
					<key>match</key>
					<string>\b(if|elseif|else|switch|case|default)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.loop.neoscript</string>
					<key>match</key>
					<string>\b(for|foreach|while|do|in|break|continue)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.neoscript</string>
					<key>match</key>
					<string>\b(return|import|export|delegate|async|await)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.function.neoscript</string>
					<key>match</key>
					<string>\b(fun)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.variable.neoscript</string>
					<key>match</key>
					<string>\b(var)\b</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.neoscript</string>
					<key>match</key>
					<string>\b(true|false|none|null|this)\b</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.neoscript</string>
			<key>match</key>
			<string>\b(?:0x[0-9A-Fa-f]+|\d+(?:\.\d+)?)\b</string>
		</dict>
		<key>function-calls</key>
		<dict>
			<key>name</key>
			<string>meta.function-call.neoscript</string>
			<key>match</key>
			<string>\b([A-Za-z_][A-Za-z0-9_]*)\s*(?=\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>support.function.neoscript</string></dict>
			</dict>
		</dict>
		<key>operators</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.neoscript</string>
			<key>match</key>
			<string>(\.\.|==|!=|&lt;=|&gt;=|&amp;&amp;|\|\||[+\-*/%=&lt;&gt;!])</string>
		</dict>
	</dict>
</dict>
</plist>
