@echo off
setlocal
REM ---------------------------------------------------------------------------
REM Profile-guided build of Samples/console (Release x64).
REM
REM Three stages: instrument -> run a training workload -> optimize.
REM The ordinary build is unaffected; console.vcxproj only switches on
REM NeoLtcgMode, which is empty unless this script sets it.
REM
REM Two traps this script exists to avoid:
REM   1. /t:Rebuild wipes the output directory, and console.pgd lives there.
REM      Stage 3 therefore deletes only the objects and relinks, so the merged
REM      profile survives. Using /t:Rebuild there fails with LNK1266.
REM   2. The instrumented exe needs pgort140.dll. Without it the process exits
REM      silently with code 0 and writes no .pgc - it does not report an error.
REM      vcvars64 puts that DLL's directory on PATH, which is why we call it.
REM
REM The merged profile (console.pgd) is a build artifact, not a source: it is
REM gitignored and regenerated by this script. Re-run after any source change
REM that matters, otherwise the optimizer places code from a stale profile.
REM ---------------------------------------------------------------------------

set ROOT=%~dp0..
set SLN=%ROOT%\Samples\console\console.sln
set OUTDIR=%ROOT%\Samples\console\x64\Release
set EXE=%OUTDIR%\console.exe
set VS=C:\Program Files\Microsoft Visual Studio\18\Community
set MSBUILD=%VS%\MSBuild\Current\Bin\amd64\MSBuild.exe

call "%VS%\VC\Auxiliary\Build\vcvars64.bat" >nul || goto :fail

echo [1/3] instrumented build
"%MSBUILD%" "%SLN%" /t:Rebuild /p:Configuration=Release /p:Platform=x64 ^
    /p:NeoLtcgMode=PGInstrument /m /v:quiet || goto :fail

echo [2/3] training run
pushd "%ROOT%\Samples\console"
REM Compiler and VM core: 2,785 compiler cases, then the host API suite.
call :train --smoke
call :train --v2smoke
popd
pushd "%ROOT%"
REM Hot dispatch loops. Repeated so the interpreter dominates the profile.
for /l %%i in (1,1,3) do call :train --file Samples\bench\bench.ns
REM Language features across the test corpus.
for %%f in (TestScript\*.ns) do call :train_script "%%f"
popd

echo [3/3] merge and optimize
pgomgr /merge "%OUTDIR%\console.pgd" >nul || goto :fail
REM Delete objects only - console.pgd has to stay for the optimizing link.
del /q "%OUTDIR%\*.obj" "%OUTDIR%\*.pgc" "%OUTDIR%\*.iobj" "%OUTDIR%\*.ipdb" "%EXE%" 2>nul
"%MSBUILD%" "%SLN%" /p:Configuration=Release /p:Platform=x64 ^
    /p:NeoLtcgMode=PGOptimization /m /v:quiet || goto :fail

echo.
echo done: %EXE%
echo verify with: console.exe --smoke  and  console.exe --v2smoke
endlocal & exit /b 0

:train
"%EXE%" %* >nul 2>&1
exit /b 0

REM Skips the scripts that block on network or sleep instead of returning:
REM they would stall the training run rather than contribute to the profile.
:train_script
set SKIP=
if /i "%~nx1"=="http.ns"         set SKIP=1
if /i "%~nx1"=="async_nested.ns" set SKIP=1
if /i "%~nx1"=="coroutine.ns"    set SKIP=1
if /i "%~nx1"=="time_limit.ns"   set SKIP=1
if defined SKIP exit /b 0
"%EXE%" --file "%~1" >nul 2>&1
exit /b 0

:fail
echo.
echo PGO build FAILED
endlocal & exit /b 1
